### ISSUE TITLE
g友是英德人？

### ISSUE THREAD

**Issue by Ch1ngg** [cnfeat/Yilee#4]
RT

**Comment by cnfeat** [comment]
是的呀。

**Comment by Ch1ngg** [comment]
:-) 我也是

2017年3月10日 17:59，"CNFeat" <notifications@github.com>写道：

**Comment by cnfeat** [comment]
哈哈，那么巧，可加微信：cnfeat

**Comment by Ch1ngg** [comment]
猴

2017年3月24日 10:46，"CNFeat" <notifications@github.com>写道：
