### ISSUE TITLE
羡慕

### ISSUE THREAD

**Issue by lkcode666666** [cnfeat/Yilee#6]
有时候想想，即使我像疯狂粉丝那样的记住了她的每一个生活习惯 喜怒哀乐 喜欢的讨厌的 估计喜欢也不会轮到我 因为不喜欢就是不喜欢吧！祝幸福！~

**Comment by cnfeat** [comment]
疯狂粉丝般，那可能不是真爱了吧，我喜欢的是相互平等的关系呀。
